apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend-biedronka
  name: backend-biedronka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-biedronka
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/projekt---technologie-chmurowe-wiktorsieracki-default: "true"
        io.kompose.service: backend-biedronka
    spec:
      containers:
        - env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: JWT_SECRET
          - name: PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: PUBLIC_KEY
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: MONGO_URI
          image: backend-biedronka
          imagePullPolicy: Never
          name: backend-biedronka
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
  status: {}