apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend-biedronka
  name: frontend-biedronka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-biedronka
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/projekt---technologie-chmurowe-wiktorsieracki-default: "true"
        io.kompose.service: frontend-biedronka
    spec:
      containers:
        - env:
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: frontend-secrets
                key: CLIENT_SECRET
          - name: NEXTAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: frontend-secrets
                key: NEXTAUTH_SECRET
          image: frontend-biedronka
          imagePullPolicy: Never
          name: frontend-biedronka
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
      restartPolicy: Always
status: {}
