apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: keycloak-biedronka
  name: keycloak-biedronka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak-biedronka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/projekt---technologie-chmurowe-wiktorsieracki-default: "true"
        io.kompose.service: keycloak-biedronka
    spec:
      containers:
        - env:
          - name: AUTH_TRUST_HOST
            value: "true"
          - name: KEYCLOAK_ADMIN
            valueFrom:
              secretKeyRef:
                name: keycloak-admin-credentials
                key: admin-user
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-admin-credentials
                key: admin-password
          - name: PROFILE
            value: dev
          image: keycloak-biedronka
          imagePullPolicy: Never
          name: keycloak-biedronka
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
