apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mongodb-biedronka
  name: mongodb-biedronka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-biedronka
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/projekt---technologie-chmurowe-wiktorsieracki-default: "true"
        io.kompose.service: mongodb-biedronka
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: secret
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
          image: mongo:latest
          name: mongodb-biedronka
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
