apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongodb-biedronka
  name: mongodb-biedronka
spec:
  type: LoadBalancer
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongodb-biedronka
status:
  loadBalancer: {}
